Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var

  basemaior, basemenor, altura: inteiro
  resu: real

Inicio

   escreva("Digite a Base Maior:")
   leia(basemaior)
   escreva("Digite a Base Menor")
   leia(basemenor)
   escreva("Digite a Altura")
   leia(altura)
   
   resu := (basemaior+basemenor)*altura/2
   escreva("Resultado:",resu)


fimalgoritmo