Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var

   qntcombustivel, porlitro, total: real


Inicio

      escreval("Quantos litros serão colocados ?")
      leia(qntcombustivel)
      escreval("Valor por litro ?")
      leia(porlitro)
      
      total := qntcombustivel*porlitro
      
      escreva("O total foi de:",total)
      
      

fimalgoritmo