Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var


  nota1, nota2, nota3: inteiro
  media: real


Inicio

  escreva("Digite a Nota 1:")
  leia(nota1)
  escreva("Digite a Nota2:")
  leia(nota2)
  escreva("Digite a Nota2:")
  leia(nota3)
  
  media := (nota1+nota2+nota3)/3

  se (media>=7) entao
     escreva("Aprovado")
     
  senao
       escreva("Reprovado")
       
  fimse

  




fimalgoritmo